apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cli-v2
  name: rollout-reporter
  namespace: t1
spec:
  eventBusName: codefresh-eventbus
  resource:
    rollouts:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: argoproj.io
      namespace: t1
      resource: rollouts
      version: v1alpha1
  template:
    serviceAccountName: rollout-reporter-sa
status: {}
